package app.vercel.danfelogarporfolios.composeapp.components.layout

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp


@Preview(
    showBackground = true
)
@Composable
fun MyColumn(
    modifier: Modifier = Modifier
){
    Column(
        modifier = modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("FeLo", modifier = Modifier.background(Color.Cyan))
        Text("Gar", modifier = Modifier.background(Color.Gray))
        Text("Dan", modifier = Modifier.background(Color.Yellow))
        Text("Gar", modifier = Modifier.background(Color.Gray))
    }
}

